# Java Custom Server configuration
host=127.0.0.1
ports=8080,8081
default_port=8080
client_body_limit=10485760

# Custom Error Pages
error.400=error_pages/400.html
error.403=error_pages/403.html
error.404=error_pages/404.html
error.405=error_pages/405.html
error.413=error_pages/413.html
error.500=error_pages/500.html

# Routes
# route.<prefix>.<key>=<value>

# Default root route
route./.root=www
route./.methods=GET,POST
route./.index=index.html
route./.dir_listing=true

# Uploads route
route./uploads.root=www/uploads
route./uploads.methods=GET,POST,DELETE
route./uploads.dir_listing=true

# CGI bin route
route./cgi-bin.root=www/cgi-bin
route./cgi-bin.methods=GET,POST
route./cgi-bin.cgi.py=python
