import os
import sys
import urllib.parse

def main():
    print("Content-Type: text/html; charset=UTF-8")
    print()

    method = os.environ.get("REQUEST_METHOD", "GET")
    query = os.environ.get("QUERY_STRING", "")
    cookie = os.environ.get("HTTP_COOKIE", "")
    path_info = os.environ.get("PATH_INFO", "")

    name = "Stranger"
    if query:
        params = urllib.parse.parse_qs(query)
        if "name" in params:
            name = params["name"][0]

    body_data = ""
    if method == "POST":
        try:
            content_length = int(os.environ.get("CONTENT_LENGTH", 0))
            if content_length > 0:
                body_data = sys.stdin.read(content_length)
        except Exception:
            pass

    html = f"""<!DOCTYPE html>
<html>
<head>
    <title>CGI Execution Result</title>
    <style>
        body {{
            background: linear-gradient(135deg, #0f0c1b, #201a30);
            color: #f1f1f1;
            font-family: 'Inter', sans-serif;
            padding: 2rem;
            display: flex;
            justify-content: center;
        }}
        .card {{
            background: rgba(255, 255, 255, 0.05);
            backdrop-filter: blur(10px);
            border: 1px solid rgba(255, 255, 255, 0.1);
            padding: 2rem;
            border-radius: 16px;
            width: 100%;
            max-width: 600px;
            box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.37);
        }}
        h1 {{ color: #c084fc; margin-top: 0; }}
        h2 {{ color: #38bdf8; font-size: 1.2rem; }}
        pre {{
            background: rgba(0,0,0,0.3);
            padding: 1rem;
            border-radius: 8px;
            overflow-x: auto;
            border: 1px solid rgba(255,255,255,0.05);
            font-size: 0.9rem;
        }}
        .back {{
            display: inline-block;
            margin-top: 1.5rem;
            color: #38bdf8;
            text-decoration: none;
        }}
    </style>
</head>
<body>
    <div class="card">
        <h1>Hello, {html_escape(name)}!</h1>
        <p>This page was dynamically generated by a Python CGI script executing on the server.</p>
        
        <h2>CGI Environment Variables</h2>
        <pre>REQUEST_METHOD: {method}
QUERY_STRING: {query}
HTTP_COOKIE: {cookie}
PATH_INFO: {path_info}</pre>

        {"<h2>POST Body Content</h2><pre>" + html_escape(body_data) + "</pre>" if body_data else ""}
        
        <a href="/" class="back">&larr; Back Home</a>
    </div>
</body>
</html>"""
    print(html)

def html_escape(text):
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;").replace("'", "&#x27;")

if __name__ == "__main__":
    main()
